# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Auto Deploy

on:
  push:
    branches: [main, staging, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build files
        run: npm run build --if-present
        
      - name: Deploy dev
        if: github.ref == 'refs/heads/dev'
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.DEV_DIR }}
          EXCLUDE: ".git*, .github*, node_modules*, webpack.config.js"

      - name: Deploy dev
        if: github.ref == 'refs/heads/dev'
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.DEV_DIR }}
          EXCLUDE: ".git*, .github*, node_modules*, webpack.config.js"

      - name: Deploy staging
        if: github.ref == 'refs/heads/staging'
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.STAGING_DIR }}
          EXCLUDE: ".git*, .github*, node_modules*, webpack.config.js"

      - name: Deploy production
        if: github.ref == 'refs/heads/main'
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.PRODUCTION_DIR }}
          EXCLUDE: ".git*, .github*, node_modules*, webpack.config.js"
